service: my-service
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: "*"
functions:
  my-function:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
